services:
  - type: web
    name: formsg-servicenow-webhook
    env: node
    plan: free
    region: singapore

    buildCommand: |
      npm install

    startCommand: |
      node app.js

    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18

      # FormSG Keys
      - key: FORM_PUBLIC_KEY
        sync: false
      - key: FORM_SECRET_KEY
        sync: false

      # ServiceNow OAuth
      - key: SN_INSTANCE
        sync: false
      - key: SN_CLIENT_ID
        sync: false
      - key: SN_CLIENT_SECRET
        sync: false

      # ServiceNow Table Name
      - key: SN_TABLE
        value: u_yrsg_case

      # Force Render port
      - key: PORT
        value: 10000

